### ISSUE TITLE
ubuntu 16.04 下编译出错：Tengine-Convert-Tools/tools/oneflow/oneflow/core/actor/act_event.pb.cc: No such file or directory

### ISSUE THREAD

**Issue by qq297110281** [OAID/Tengine-Convert-Tools#30]
尝试在ubuntu 16.04下编译时报错：
Tengine-Convert-Tools/tools/oneflow/oneflow/core/actor/act_event.pb.cc: No such file or directory

cmake版本：3.11.1
protobuf版本:3.14.0
报错截图：
![image](https://user-images.githubusercontent.com/8348315/107022581-8bc1c800-67e0-11eb-8c6e-e68cb8dc1735.png)

**Comment by BUG1989** [comment]
可以通过添加编译选项 cmake -DBUILD_ONEFLOW_SERIALIZER=OFF .. 暂时关闭再试试。
